language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
sudo: false
install:
  - sudo apt-get install python3-pyqt5.qtmultimedia
  - pip install --upgrade pip
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - pylint --rcfile=.pylintrc deploy.py game.py jackit2 jackitio/jackitio jackitio/leaderboard jackitio/manage.py
  - pycodestyle deploy.py game.py jackit2 jackitio/jackitio jackitio/leaderboard jackitio/manage.py
  - pytest --cov jackit2
