language: python
python:
  - "3.7"
sudo: false
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - pylint --rcfile=.pylintrc deploy.py game.py jackit2 jackitio/jackitio jackitio/leaderboard jackitio/manage.py
  - pycodestyle deploy.py game.py jackit2 jackitio/jackitio jackitio/leaderboard jackitio/manage.py
