language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
sudo: false
before_install:
  - git lfs pull
install:
  - python -m pip install --upgrade pip
  - pip install tox-travis tox coveralls
script:
  - tox
after_success:
  - coveralls
